# Generated by Django 4.1.3 on 2022-12-06 10:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Index_First_Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Index_First')),
            ],
            options={
                'verbose_name': 'Index First Slider',
                'verbose_name_plural': 'Index First Silders',
            },
        ),
        migrations.CreateModel(
            name='Index_Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_image', models.FileField(upload_to='Main Index')),
                ('name_part', models.CharField(max_length=50, null=True)),
                ('profession', models.CharField(max_length=50, null=True)),
                ('text_1', models.TextField(null=True)),
                ('image_1', models.ImageField(null=True, upload_to='Who am I')),
                ('image_2', models.ImageField(null=True, upload_to='Who am I')),
                ('image_3', models.ImageField(null=True, upload_to='Who am I')),
                ('text_2', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
            ],
            options={
                'verbose_name': 'Index Settings',
                'verbose_name_plural': 'Index Settings',
            },
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('logo', models.FileField(upload_to='Services')),
            ],
            options={
                'verbose_name': 'Service',
                'verbose_name_plural': 'Services',
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.services')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
    ]
