# Generated by Django 4.1.3 on 2022-12-06 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='created_date',
        ),
    ]
