# Generated by Django 4.1.3 on 2022-12-06 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_images_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created_date',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
