# Generated by Django 4.1.3 on 2022-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_images_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
