# Generated by Django 4.1.3 on 2022-12-07 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_booking_alter_offers_options_alter_options_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='services',
            name='slug',
            field=models.SlugField(editable=False, null=True),
        ),
    ]
