# Generated by Django 4.1.3 on 2022-12-08 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_why_us_detail_why_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='why_options',
            options={'verbose_name': 'Why Us Options', 'verbose_name_plural': 'Why Us Options'},
        ),
        migrations.AddField(
            model_name='booking',
            name='service',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='why_options',
            name='why',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='blog.why_us_detail'),
        ),
    ]
