# Generated by Django 4.1.3 on 2022-12-10 13:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_category_options_main_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service_Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='Images')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.services')),
            ],
            options={
                'verbose_name': 'Image',
                'verbose_name_plural': 'Images',
            },
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'verbose_name': 'Main Image', 'verbose_name_plural': 'Main Images'},
        ),
        migrations.RemoveField(
            model_name='images',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='images',
            name='service',
        ),
        migrations.AddField(
            model_name='images',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='blog.category'),
        ),
        migrations.AlterField(
            model_name='images',
            name='image',
            field=models.ImageField(upload_to='Main_Images'),
        ),
        migrations.DeleteModel(
            name='Main_Images',
        ),
    ]
