# Generated by Django 4.1.3 on 2022-12-10 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_work_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='client',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='work',
            name='location',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
