# Generated by Django 4.1.3 on 2022-12-10 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_work_client_work_date_work_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='work',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
